twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'

    strict_variables: '%kernel.debug%'
    globals:
        switcher: '@App\Controller\LanguageSwitcherController'
        searchbar: '@App\Controller\ForumSearchController'
    form_theme: 'bootstrap_4_layout.html.twig'
